export const GET_ALL_RIDES_REQUEST = "GET_ALL_RIDES_REQUEST";
export const GET_ALL_RIDES_SUCCESS = "GET_ALL_RIDES_SUCCESS";
export const GET_ALL_RIDES_FAILED = "GET_ALL_RIDES_FAILED";

export const SELECT_RIDE = 'SELECT_RIDE';


